In [198]:
#Import
import numpy as np 
import pandas as pd

In [199]:
#Load data
df = pd.read_csv('students_data.csv')

In [200]:
#Show the datas 
df

    student_id              name  math  English  science  attendance
0            1     Alice Johnson    85       92       78          94
1            2         Bob Smith    70       65       80          72
2            3     Charlie Brown    95       88       92          96
3            4      David Wilson    50       45       55          61
4            5      Eva Martinez    88       91       83          93
5            6      Frank Thomas    76       84       79          88
6            7         Grace Lee    82       79       85          90
7            8      Henry Walker    90       87       91          95
8            9       Isla Harris    68       72       74          75
9           10     Jack Robinson    77       85       80          89
10          11        Kara Lewis    83       89       86          92
11          12        Liam Young    91       94       90          97
12          13         Mia Allen    73       80       77          84
13          14         Noah King    65       70       68          70
14          15     Olivia Wright    87       93       89          94
15          16        Paul Scott    79       81       82          86
16          17      Quinn Torres    84       88       85          91
17          18       Ryan Nguyen    92       90       95          98
18          19       Sophia Hill    75       78       76          83
19          20      Thomas Adams    81       83       80          88
20          21         Uma Baker    89       92       88          95
21          22   Victor Gonzalez    68       71       73          74
22          23      Wendy Carter    86       90       87          93
23          24   Xavier Mitchell    77       79       81          85
24          25        Yara Perez    93       95       94          98
25          26      Zane Roberts    64       67       66          69
26          27        Ava Murphy    85       88       83          92
27          28      Blake Rivera    72       74       70          80
28          29      Chloe Brooks    90       91       92          96
29          30     Dylan Sanders    78       80       79          85
30          31       Ella Foster    87       89       88          94
31          32        Finn Kelly    83       84       85          90
32          33  Gabriella Howard    91       93       92          97
33          34       Hudson Ward    66       70       68          72
34          35      Isabelle Cox    88       90       87          94
35          36       Jasper Diaz    79       81       82          86
36          37  Kylie Richardson    84       86       85          91
37          38      Logan Watson    92       94       91          97
38          39     Madison Perry    75       77       74          82
39          40     Nathan Powell    81       82       80          87
40          41        Olive Long    89       91       88          95
41          42  Parker Patterson    70       73       72          76
42          43     Quincy Hughes    86       88       85          92
43          44      Riley Flores    77       79       78          84
44          45  Savannah Bennett    93       95       94          98
45          46     Tyler Simmons    65       68       67          71
46          47   Victoria Foster    85       87       86          93
47          48      Wyatt Bryant    73       75       74          81
48          49      Ximena Hayes    90       92       91          96
49          50     Yusuf Russell    78       80       79          85

In [201]:
#Show the information about the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  50 non-null     int64
 1   name        50 non-null     str
 2   math        50 non-null     int64
 3   English     50 non-null     int64
 4   science     50 non-null     int64
 5   attendance  50 non-null     int64
dtypes: int64(5), str(1)
memory usage: 2.5 KB

In [202]:
#Show the shape of the data
df.shape

(50, 6)

In [203]:
#Calculate total marks per student 
df['Total_Marks'] = df[['math', 'English', 'science']].sum(axis=1)

In [204]:
#Display the updated DataFrame
df

,student_id,name,math,English,science,attendance,Total_Marks
0,1,Alice Johnson,85,92,78,94,255
1,2,Bob Smith,70,65,80,72,215
2,3,Charlie Brown,95,88,92,96,275
3,4,David Wilson,50,45,55,61,150
4,5,Eva Martinez,88,91,83,93,262
5,6,Frank Thomas,76,84,79,88,239
6,7,Grace Lee,82,79,85,90,246
7,8,Henry Walker,90,87,91,95,268
8,9,Isla Harris,68,72,74,75,214
9,10,Jack Robinson,77,85,80,89,242
10,11,Kara Lewis,83,89,86,92,258
11,12,Liam Young,91,94,90,97,275
12,13,Mia Allen,73,80,77,84,230
13,14,Noah King,65,70,68,70,203
14,15,Olivia Wright,87,93,89,94,269
15,16,Paul Scott,79,81,82,86,242
16,17,Quinn Torres,84,88,85,91,257
17,18,Ryan Nguyen,92,90,95,98,277
18,19,Sophia Hill,75,78,76,83,229
19,20,Thomas Adams,81,83,80,88,244
20,21,Uma Baker,89,92,88,95,269
21,22,Victor Gonzalez,68,71,73,74,212
22,23,Wendy Carter,86,90,87,93,263
23,24,Xavier Mitchell,77,79,81,85,237
24,25,Yara Perez,93,95,94,98,282
25,26,Zane Roberts,64,67,66,69,197
26,27,Ava Murphy,85,88,83,92,256
27,28,Blake Rivera,72,74,70,80,216
28,29,Chloe Brooks,90,91,92,96,273
29,30,Dylan Sanders,78,80,79,85,237
30,31,Ella Foster,87,89,88,94,264
31,32,Finn Kelly,83,84,85,90,252
32,33,Gabriella Howard,91,93,92,97,276
33,34,Hudson Ward,66,70,68,72,204
34,35,Isabelle Cox,88,90,87,94,265
35,36,Jasper Diaz,79,81,82,86,242
36,37,Kylie Richardson,84,86,85,91,255
37,38,Logan Watson,92,94,91,97,277
38,39,Madison Perry,75,77,74,82,226
39,40,Nathan Powell,81,82,80,87,243
40,41,Olive Long,89,91,88,95,268
41,42,Parker Patterson,70,73,72,76,215
42,43,Quincy Hughes,86,88,85,92,259
43,44,Riley Flores,77,79,78,84,234
44,45,Savannah Bennett,93,95,94,98,282
45,46,Tyler Simmons,65,68,67,71,200
46,47,Victoria Foster,85,87,86,93,258
47,48,Wyatt Bryant,73,75,74,81,222
48,49,Ximena Hayes,90,92,91,96,273
49,50,Yusuf Russell,78,80,79,85,237

In [205]:
#Calculate Avg marks per student
df['Average_Marks'] = df[['math', 'English', 'science']].mean(axis=1).round(2)

In [206]:
#Display updated DataFrame
df

,student_id,name,math,English,science,attendance,Total_Marks,Average_Marks
0,1,Alice Johnson,85,92,78,94,255,85.00
1,2,Bob Smith,70,65,80,72,215,71.67
2,3,Charlie Brown,95,88,92,96,275,91.67
3,4,David Wilson,50,45,55,61,150,50.00
4,5,Eva Martinez,88,91,83,93,262,87.33
5,6,Frank Thomas,76,84,79,88,239,79.67
6,7,Grace Lee,82,79,85,90,246,82.00
7,8,Henry Walker,90,87,91,95,268,89.33
8,9,Isla Harris,68,72,74,75,214,71.33
9,10,Jack Robinson,77,85,80,89,242,80.67
10,11,Kara Lewis,83,89,86,92,258,86.00
11,12,Liam Young,91,94,90,97,275,91.67
12,13,Mia Allen,73,80,77,84,230,76.67
13,14,Noah King,65,70,68,70,203,67.67
14,15,Olivia Wright,87,93,89,94,269,89.67
15,16,Paul Scott,79,81,82,86,242,80.67
16,17,Quinn Torres,84,88,85,91,257,85.67
17,18,Ryan Nguyen,92,90,95,98,277,92.33
18,19,Sophia Hill,75,78,76,83,229,76.33
19,20,Thomas Adams,81,83,80,88,244,81.33
20,21,Uma Baker,89,92,88,95,269,89.67
21,22,Victor Gonzalez,68,71,73,74,212,70.67
22,23,Wendy Carter,86,90,87,93,263,87.67
23,24,Xavier Mitchell,77,79,81,85,237,79.00
24,25,Yara Perez,93,95,94,98,282,94.00
25,26,Zane Roberts,64,67,66,69,197,65.67
26,27,Ava Murphy,85,88,83,92,256,85.33
27,28,Blake Rivera,72,74,70,80,216,72.00
28,29,Chloe Brooks,90,91,92,96,273,91.00
29,30,Dylan Sanders,78,80,79,85,237,79.00
30,31,Ella Foster,87,89,88,94,264,88.00
31,32,Finn Kelly,83,84,85,90,252,84.00
32,33,Gabriella Howard,91,93,92,97,276,92.00
33,34,Hudson Ward,66,70,68,72,204,68.00
34,35,Isabelle Cox,88,90,87,94,265,88.33
35,36,Jasper Diaz,79,81,82,86,242,80.67
36,37,Kylie Richardson,84,86,85,91,255,85.00
37,38,Logan Watson,92,94,91,97,277,92.33
38,39,Madison Perry,75,77,74,82,226,75.33
39,40,Nathan Powell,81,82,80,87,243,81.00
40,41,Olive Long,89,91,88,95,268,89.33
41,42,Parker Patterson,70,73,72,76,215,71.67
42,43,Quincy Hughes,86,88,85,92,259,86.33
43,44,Riley Flores,77,79,78,84,234,78.00
44,45,Savannah Bennett,93,95,94,98,282,94.00
45,46,Tyler Simmons,65,68,67,71,200,66.67
46,47,Victoria Foster,85,87,86,93,258,86.00
47,48,Wyatt Bryant,73,75,74,81,222,74.00
48,49,Ximena Hayes,90,92,91,96,273,91.00
49,50,Yusuf Russell,78,80,79,85,237,79.00

In [207]:
#Students with attendance ≥ 90%
df.loc[df['attendance'] >= 90, ['student_id', 'name', 'attendance']]

    student_id              name  attendance
0            1     Alice Johnson          94
2            3     Charlie Brown          96
4            5      Eva Martinez          93
6            7         Grace Lee          90
7            8      Henry Walker          95
10          11        Kara Lewis          92
11          12        Liam Young          97
14          15     Olivia Wright          94
16          17      Quinn Torres          91
17          18       Ryan Nguyen          98
20          21         Uma Baker          95
22          23      Wendy Carter          93
24          25        Yara Perez          98
26          27        Ava Murphy          92
28          29      Chloe Brooks          96
30          31       Ella Foster          94
31          32        Finn Kelly          90
32          33  Gabriella Howard          97
34          35      Isabelle Cox          94
36          37  Kylie Richardson          91
37          38      Logan Watson          97
40          41        Olive Long          95
42          43     Quincy Hughes          92
44          45  Savannah Bennett          98
46          47   Victoria Foster          93
48          49      Ximena Hayes          96

In [208]:
# Students with attendance < 80%
df.loc[df['attendance'] < 80, ['student_id', 'name', 'attendance']]

    student_id              name  attendance
1            2         Bob Smith          72
3            4      David Wilson          61
8            9       Isla Harris          75
13          14         Noah King          70
21          22   Victor Gonzalez          74
25          26      Zane Roberts          69
33          34       Hudson Ward          72
41          42  Parker Patterson          76
45          46     Tyler Simmons          71

In [209]:
#Students high attendance (≥ 65%)
high_attendance = df.loc[df["attendance"] >= 65, ['student_id', 'name', 'attendance']]
high_attendance

    student_id              name  attendance
0            1     Alice Johnson          94
1            2         Bob Smith          72
2            3     Charlie Brown          96
4            5      Eva Martinez          93
5            6      Frank Thomas          88
6            7         Grace Lee          90
7            8      Henry Walker          95
8            9       Isla Harris          75
9           10     Jack Robinson          89
10          11        Kara Lewis          92
11          12        Liam Young          97
12          13         Mia Allen          84
13          14         Noah King          70
14          15     Olivia Wright          94
15          16        Paul Scott          86
16          17      Quinn Torres          91
17          18       Ryan Nguyen          98
18          19       Sophia Hill          83
19          20      Thomas Adams          88
20          21         Uma Baker          95
21          22   Victor Gonzalez          74
22          23      Wendy Carter          93
23          24   Xavier Mitchell          85
24          25        Yara Perez          98
25          26      Zane Roberts          69
26          27        Ava Murphy          92
27          28      Blake Rivera          80
28          29      Chloe Brooks          96
29          30     Dylan Sanders          85
30          31       Ella Foster          94
31          32        Finn Kelly          90
32          33  Gabriella Howard          97
33          34       Hudson Ward          72
34          35      Isabelle Cox          94
35          36       Jasper Diaz          86
36          37  Kylie Richardson          91
37          38      Logan Watson          97
38          39     Madison Perry          82
39          40     Nathan Powell          87
40          41        Olive Long          95
41          42  Parker Patterson          76
42          43     Quincy Hughes          92
43          44      Riley Flores          84
44          45  Savannah Bennett          98
45          46     Tyler Simmons          71
46          47   Victoria Foster          93
47          48      Wyatt Bryant          81
48          49      Ximena Hayes          96
49          50     Yusuf Russell          85

In [210]:
#Students low attendance (< 65)
low_attendance  = df.loc[df["attendance"] < 65, ['student_id', 'name', 'attendance']]
low_attendance

   student_id          name  attendance
3           4  David Wilson          61

In [211]:
#Students each subject totals
subject_totals = df[['math', 'English', 'science']].sum()

In [212]:
# Create new row "Total Each Subject" with student_id and student_name as empty
total_each_marks = pd.DataFrame([{
    'student_id': '',
    'name': 'Total Each Subject',
    'math': subject_totals['math'],
    'English': subject_totals['English'],
    'science': subject_totals['science']
}])

In [213]:
#Students each subject averages
each_subject_averages = df[['math', 'English', 'science']].mean().round(2)

In [214]:
# Create new row "Average Each Subject"
each_avg_marks = pd.DataFrame([{
    'student_id': '',
    'name': 'Average Each Subject',
    'math': each_subject_averages['math'],
    'English': each_subject_averages['English'],
    'science': each_subject_averages['science']
}])

In [215]:
#Combine original DataFrame with total and average rows
df_each_subject = pd.concat([df, total_each_marks, each_avg_marks], ignore_index=True)

In [216]:
#Display the updated DataFrame
df_each_subject

,student_id,name,math,English,science,attendance,Total_Marks,Average_Marks
0,1,Alice Johnson,85.0,92.0,78.00,94.0,255.0,85.00
1,2,Bob Smith,70.0,65.0,80.00,72.0,215.0,71.67
2,3,Charlie Brown,95.0,88.0,92.00,96.0,275.0,91.67
3,4,David Wilson,50.0,45.0,55.00,61.0,150.0,50.00
4,5,Eva Martinez,88.0,91.0,83.00,93.0,262.0,87.33
5,6,Frank Thomas,76.0,84.0,79.00,88.0,239.0,79.67
6,7,Grace Lee,82.0,79.0,85.00,90.0,246.0,82.00
7,8,Henry Walker,90.0,87.0,91.00,95.0,268.0,89.33
8,9,Isla Harris,68.0,72.0,74.00,75.0,214.0,71.33
9,10,Jack Robinson,77.0,85.0,80.00,89.0,242.0,80.67
10,11,Kara Lewis,83.0,89.0,86.00,92.0,258.0,86.00
11,12,Liam Young,91.0,94.0,90.00,97.0,275.0,91.67
12,13,Mia Allen,73.0,80.0,77.00,84.0,230.0,76.67
13,14,Noah King,65.0,70.0,68.00,70.0,203.0,67.67
14,15,Olivia Wright,87.0,93.0,89.00,94.0,269.0,89.67
15,16,Paul Scott,79.0,81.0,82.00,86.0,242.0,80.67
16,17,Quinn Torres,84.0,88.0,85.00,91.0,257.0,85.67
17,18,Ryan Nguyen,92.0,90.0,95.00,98.0,277.0,92.33
18,19,Sophia Hill,75.0,78.0,76.00,83.0,229.0,76.33
19,20,Thomas Adams,81.0,83.0,80.00,88.0,244.0,81.33
20,21,Uma Baker,89.0,92.0,88.00,95.0,269.0,89.67
21,22,Victor Gonzalez,68.0,71.0,73.00,74.0,212.0,70.67
22,23,Wendy Carter,86.0,90.0,87.00,93.0,263.0,87.67
23,24,Xavier Mitchell,77.0,79.0,81.00,85.0,237.0,79.00
24,25,Yara Perez,93.0,95.0,94.00,98.0,282.0,94.00
25,26,Zane Roberts,64.0,67.0,66.00,69.0,197.0,65.67
26,27,Ava Murphy,85.0,88.0,83.00,92.0,256.0,85.33
27,28,Blake Rivera,72.0,74.0,70.00,80.0,216.0,72.00
28,29,Chloe Brooks,90.0,91.0,92.00,96.0,273.0,91.00
29,30,Dylan Sanders,78.0,80.0,79.00,85.0,237.0,79.00
30,31,Ella Foster,87.0,89.0,88.00,94.0,264.0,88.00
31,32,Finn Kelly,83.0,84.0,85.00,90.0,252.0,84.00
32,33,Gabriella Howard,91.0,93.0,92.00,97.0,276.0,92.00
33,34,Hudson Ward,66.0,70.0,68.00,72.0,204.0,68.00
34,35,Isabelle Cox,88.0,90.0,87.00,94.0,265.0,88.33
35,36,Jasper Diaz,79.0,81.0,82.00,86.0,242.0,80.67
36,37,Kylie Richardson,84.0,86.0,85.00,91.0,255.0,85.00
37,38,Logan Watson,92.0,94.0,91.00,97.0,277.0,92.33
38,39,Madison Perry,75.0,77.0,74.00,82.0,226.0,75.33
39,40,Nathan Powell,81.0,82.0,80.00,87.0,243.0,81.00
40,41,Olive Long,89.0,91.0,88.00,95.0,268.0,89.33
41,42,Parker Patterson,70.0,73.0,72.00,76.0,215.0,71.67
42,43,Quincy Hughes,86.0,88.0,85.00,92.0,259.0,86.33
43,44,Riley Flores,77.0,79.0,78.00,84.0,234.0,78.00
44,45,Savannah Bennett,93.0,95.0,94.00,98.0,282.0,94.00
45,46,Tyler Simmons,65.0,68.0,67.00,71.0,200.0,66.67
46,47,Victoria Foster,85.0,87.0,86.00,93.0,258.0,86.00
47,48,Wyatt Bryant,73.0,75.0,74.00,81.0,222.0,74.00
48,49,Ximena Hayes,90.0,92.0,91.00,96.0,273.0,91.00
49,50,Yusuf Russell,78.0,80.0,79.00,85.0,237.0,79.00
50,,Total Each Subject,4025.0,4135.0,4084.00,NaN,NaN,NaN
51,,Average Each Subject,80.5,82.7,81.68,NaN,NaN,NaN

In [217]:
#Overall class average
overall_class_avg = float(df['Average_Marks'].mean().round(2))

In [218]:
overall_class_avg

81.63

In [219]:
# Only consider actual students
df_students_only = df_each_subject.iloc[:-2].copy()

In [220]:
# Top-performing student
top_student = df_students_only.loc[
    df_students_only['Total_Marks'].idxmax(),
    ['student_id', 'name', 'Total_Marks', 'Average_Marks']
]

In [221]:
top_student

student_id               25
name             Yara Perez
Total_Marks           282.0
Average_Marks          94.0
Name: 24, dtype: object

In [222]:
# Lowest-performing student
lowest_student = df_students_only.loc[
    df_students_only['Total_Marks'].idxmin(),
    ['student_id', 'name', 'Total_Marks', 'Average_Marks']
]

In [223]:
lowest_student

student_id                  4
name             David Wilson
Total_Marks             150.0
Average_Marks            50.0
Name: 3, dtype: object

In [224]:
# Sort students by Average_Marks (descending)
df_sorted = df.sort_values(by='Average_Marks', ascending=False).reset_index(drop=True)

In [225]:
df_sorted

,student_id,name,math,English,science,attendance,Total_Marks,Average_Marks
0,25,Yara Perez,93,95,94,98,282,94.00
1,45,Savannah Bennett,93,95,94,98,282,94.00
2,38,Logan Watson,92,94,91,97,277,92.33
3,18,Ryan Nguyen,92,90,95,98,277,92.33
4,33,Gabriella Howard,91,93,92,97,276,92.00
5,12,Liam Young,91,94,90,97,275,91.67
6,3,Charlie Brown,95,88,92,96,275,91.67
7,49,Ximena Hayes,90,92,91,96,273,91.00
8,29,Chloe Brooks,90,91,92,96,273,91.00
9,21,Uma Baker,89,92,88,95,269,89.67
10,15,Olivia Wright,87,93,89,94,269,89.67
11,8,Henry Walker,90,87,91,95,268,89.33
12,41,Olive Long,89,91,88,95,268,89.33
13,35,Isabelle Cox,88,90,87,94,265,88.33
14,31,Ella Foster,87,89,88,94,264,88.00
15,23,Wendy Carter,86,90,87,93,263,87.67
16,5,Eva Martinez,88,91,83,93,262,87.33
17,43,Quincy Hughes,86,88,85,92,259,86.33
18,11,Kara Lewis,83,89,86,92,258,86.00
19,47,Victoria Foster,85,87,86,93,258,86.00
20,17,Quinn Torres,84,88,85,91,257,85.67
21,27,Ava Murphy,85,88,83,92,256,85.33
22,37,Kylie Richardson,84,86,85,91,255,85.00
23,1,Alice Johnson,85,92,78,94,255,85.00
24,32,Finn Kelly,83,84,85,90,252,84.00
25,7,Grace Lee,82,79,85,90,246,82.00
26,20,Thomas Adams,81,83,80,88,244,81.33
27,40,Nathan Powell,81,82,80,87,243,81.00
28,16,Paul Scott,79,81,82,86,242,80.67
29,36,Jasper Diaz,79,81,82,86,242,80.67
30,10,Jack Robinson,77,85,80,89,242,80.67
31,6,Frank Thomas,76,84,79,88,239,79.67
32,50,Yusuf Russell,78,80,79,85,237,79.00
33,24,Xavier Mitchell,77,79,81,85,237,79.00
34,30,Dylan Sanders,78,80,79,85,237,79.00
35,44,Riley Flores,77,79,78,84,234,78.00
36,13,Mia Allen,73,80,77,84,230,76.67
37,19,Sophia Hill,75,78,76,83,229,76.33
38,39,Madison Perry,75,77,74,82,226,75.33
39,48,Wyatt Bryant,73,75,74,81,222,74.00
40,28,Blake Rivera,72,74,70,80,216,72.00
41,42,Parker Patterson,70,73,72,76,215,71.67
42,2,Bob Smith,70,65,80,72,215,71.67
43,9,Isla Harris,68,72,74,75,214,71.33
44,22,Victor Gonzalez,68,71,73,74,212,70.67
45,34,Hudson Ward,66,70,68,72,204,68.00
46,14,Noah King,65,70,68,70,203,67.67
47,46,Tyler Simmons,65,68,67,71,200,66.67
48,26,Zane Roberts,64,67,66,69,197,65.67
49,4,David Wilson,50,45,55,61,150,50.00

In [226]:
# Generate Rank column
df_sorted['Rank'] = df_sorted['Average_Marks'].rank(method='min', ascending=False).astype(int)

In [227]:
df_sorted

,student_id,name,math,English,science,attendance,Total_Marks,Average_Marks,Rank
0,25,Yara Perez,93,95,94,98,282,94.00,1
1,45,Savannah Bennett,93,95,94,98,282,94.00,1
2,38,Logan Watson,92,94,91,97,277,92.33,3
3,18,Ryan Nguyen,92,90,95,98,277,92.33,3
4,33,Gabriella Howard,91,93,92,97,276,92.00,5
5,12,Liam Young,91,94,90,97,275,91.67,6
6,3,Charlie Brown,95,88,92,96,275,91.67,6
7,49,Ximena Hayes,90,92,91,96,273,91.00,8
8,29,Chloe Brooks,90,91,92,96,273,91.00,8
9,21,Uma Baker,89,92,88,95,269,89.67,10
10,15,Olivia Wright,87,93,89,94,269,89.67,10
11,8,Henry Walker,90,87,91,95,268,89.33,12
12,41,Olive Long,89,91,88,95,268,89.33,12
13,35,Isabelle Cox,88,90,87,94,265,88.33,14
14,31,Ella Foster,87,89,88,94,264,88.00,15
15,23,Wendy Carter,86,90,87,93,263,87.67,16
16,5,Eva Martinez,88,91,83,93,262,87.33,17
17,43,Quincy Hughes,86,88,85,92,259,86.33,18
18,11,Kara Lewis,83,89,86,92,258,86.00,19
19,47,Victoria Foster,85,87,86,93,258,86.00,19
20,17,Quinn Torres,84,88,85,91,257,85.67,21
21,27,Ava Murphy,85,88,83,92,256,85.33,22
22,37,Kylie Richardson,84,86,85,91,255,85.00,23
23,1,Alice Johnson,85,92,78,94,255,85.00,23
24,32,Finn Kelly,83,84,85,90,252,84.00,25
25,7,Grace Lee,82,79,85,90,246,82.00,26
26,20,Thomas Adams,81,83,80,88,244,81.33,27
27,40,Nathan Powell,81,82,80,87,243,81.00,28
28,16,Paul Scott,79,81,82,86,242,80.67,29
29,36,Jasper Diaz,79,81,82,86,242,80.67,29
30,10,Jack Robinson,77,85,80,89,242,80.67,29
31,6,Frank Thomas,76,84,79,88,239,79.67,32
32,50,Yusuf Russell,78,80,79,85,237,79.00,33
33,24,Xavier Mitchell,77,79,81,85,237,79.00,33
34,30,Dylan Sanders,78,80,79,85,237,79.00,33
35,44,Riley Flores,77,79,78,84,234,78.00,36
36,13,Mia Allen,73,80,77,84,230,76.67,37
37,19,Sophia Hill,75,78,76,83,229,76.33,38
38,39,Madison Perry,75,77,74,82,226,75.33,39
39,48,Wyatt Bryant,73,75,74,81,222,74.00,40
40,28,Blake Rivera,72,74,70,80,216,72.00,41
41,42,Parker Patterson,70,73,72,76,215,71.67,42
42,2,Bob Smith,70,65,80,72,215,71.67,42
43,9,Isla Harris,68,72,74,75,214,71.33,44
44,22,Victor Gonzalez,68,71,73,74,212,70.67,45
45,34,Hudson Ward,66,70,68,72,204,68.00,46
46,14,Noah King,65,70,68,70,203,67.67,47
47,46,Tyler Simmons,65,68,67,71,200,66.67,48
48,26,Zane Roberts,64,67,66,69,197,65.67,49
49,4,David Wilson,50,45,55,61,150,50.00,50

In [228]:
# Generate Rank column
df_sorted['Rank'] = df_sorted['Average_Marks'].rank(method='min', ascending=False).astype(int)

In [229]:
# 7️⃣ Prepare extra rows with NaN for Total_Marks, Average_Marks, Rank
extra_rows = df_each_subject.iloc[-2:].copy()
extra_rows['Total_Marks'] = pd.NA
extra_rows['Average_Marks'] = pd.NA
extra_rows['Rank'] = pd.NA

In [230]:
#Combine sorted students with extra rows
final_report = pd.concat([df_sorted, total_each_marks, each_avg_marks], ignore_index=True)

In [231]:
#Convert Rank column to Int64 (allows NaN in extra rows but keeps integers for students)
final_report['Rank'] = final_report['Rank'].astype('Int64')

In [232]:
#Export to CSV
final_report.to_csv('student_report.csv', index=False)

In [233]:
final_report

,student_id,name,math,English,science,attendance,Total_Marks,Average_Marks,Rank
0,25,Yara Perez,93.0,95.0,94.00,98.0,282.0,94.00,1
1,45,Savannah Bennett,93.0,95.0,94.00,98.0,282.0,94.00,1
2,38,Logan Watson,92.0,94.0,91.00,97.0,277.0,92.33,3
3,18,Ryan Nguyen,92.0,90.0,95.00,98.0,277.0,92.33,3
4,33,Gabriella Howard,91.0,93.0,92.00,97.0,276.0,92.00,5
5,12,Liam Young,91.0,94.0,90.00,97.0,275.0,91.67,6
6,3,Charlie Brown,95.0,88.0,92.00,96.0,275.0,91.67,6
7,49,Ximena Hayes,90.0,92.0,91.00,96.0,273.0,91.00,8
8,29,Chloe Brooks,90.0,91.0,92.00,96.0,273.0,91.00,8
9,21,Uma Baker,89.0,92.0,88.00,95.0,269.0,89.67,10
10,15,Olivia Wright,87.0,93.0,89.00,94.0,269.0,89.67,10
11,8,Henry Walker,90.0,87.0,91.00,95.0,268.0,89.33,12
12,41,Olive Long,89.0,91.0,88.00,95.0,268.0,89.33,12
13,35,Isabelle Cox,88.0,90.0,87.00,94.0,265.0,88.33,14
14,31,Ella Foster,87.0,89.0,88.00,94.0,264.0,88.00,15
15,23,Wendy Carter,86.0,90.0,87.00,93.0,263.0,87.67,16
16,5,Eva Martinez,88.0,91.0,83.00,93.0,262.0,87.33,17
17,43,Quincy Hughes,86.0,88.0,85.00,92.0,259.0,86.33,18
18,11,Kara Lewis,83.0,89.0,86.00,92.0,258.0,86.00,19
19,47,Victoria Foster,85.0,87.0,86.00,93.0,258.0,86.00,19
20,17,Quinn Torres,84.0,88.0,85.00,91.0,257.0,85.67,21
21,27,Ava Murphy,85.0,88.0,83.00,92.0,256.0,85.33,22
22,37,Kylie Richardson,84.0,86.0,85.00,91.0,255.0,85.00,23
23,1,Alice Johnson,85.0,92.0,78.00,94.0,255.0,85.00,23
24,32,Finn Kelly,83.0,84.0,85.00,90.0,252.0,84.00,25
25,7,Grace Lee,82.0,79.0,85.00,90.0,246.0,82.00,26
26,20,Thomas Adams,81.0,83.0,80.00,88.0,244.0,81.33,27
27,40,Nathan Powell,81.0,82.0,80.00,87.0,243.0,81.00,28
28,16,Paul Scott,79.0,81.0,82.00,86.0,242.0,80.67,29
29,36,Jasper Diaz,79.0,81.0,82.00,86.0,242.0,80.67,29
30,10,Jack Robinson,77.0,85.0,80.00,89.0,242.0,80.67,29
31,6,Frank Thomas,76.0,84.0,79.00,88.0,239.0,79.67,32
32,50,Yusuf Russell,78.0,80.0,79.00,85.0,237.0,79.00,33
33,24,Xavier Mitchell,77.0,79.0,81.00,85.0,237.0,79.00,33
34,30,Dylan Sanders,78.0,80.0,79.00,85.0,237.0,79.00,33
35,44,Riley Flores,77.0,79.0,78.00,84.0,234.0,78.00,36
36,13,Mia Allen,73.0,80.0,77.00,84.0,230.0,76.67,37
37,19,Sophia Hill,75.0,78.0,76.00,83.0,229.0,76.33,38
38,39,Madison Perry,75.0,77.0,74.00,82.0,226.0,75.33,39
39,48,Wyatt Bryant,73.0,75.0,74.00,81.0,222.0,74.00,40
40,28,Blake Rivera,72.0,74.0,70.00,80.0,216.0,72.00,41
41,42,Parker Patterson,70.0,73.0,72.00,76.0,215.0,71.67,42
42,2,Bob Smith,70.0,65.0,80.00,72.0,215.0,71.67,42
43,9,Isla Harris,68.0,72.0,74.00,75.0,214.0,71.33,44
44,22,Victor Gonzalez,68.0,71.0,73.00,74.0,212.0,70.67,45
45,34,Hudson Ward,66.0,70.0,68.00,72.0,204.0,68.00,46
46,14,Noah King,65.0,70.0,68.00,70.0,203.0,67.67,47
47,46,Tyler Simmons,65.0,68.0,67.00,71.0,200.0,66.67,48
48,26,Zane Roberts,64.0,67.0,66.00,69.0,197.0,65.67,49
49,4,David Wilson,50.0,45.0,55.00,61.0,150.0,50.00,50
50,,Total Each Subject,4025.0,4135.0,4084.00,NaN,NaN,NaN,<NA>
51,,Average Each Subject,80.5,82.7,81.68,NaN,NaN,NaN,<NA>