In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('student.csv')

In [4]:
#Print first 5 rows
df.head()

   id           name  math  english  science
0   1  Alice Johnson    85       92       78
1   2      Bob Smith    70       65       80
2   3  Charlie Brown    95       88       92
3   4   David Wilson    50       45       55
4   5   Eva Martinez    88       91       83

In [5]:
#Print last 5 rows
df.tail()

     id               name  math  english  science
95   96  Sebastian Bennett    79       81       80
96   97      Tessa Simmons    84       86       85
97   98     Ulysses Foster    92       94       93
98   99     Valeria Bryant    74       76       75
99  100        Wyatt Hayes    81       83       82

In [6]:
#Print column names
df.columns

Index(['id', 'name', 'math', 'english', 'science'], dtype='str')

In [19]:
print(df.columns.tolist())

['id', 'name', 'math', 'english', 'science']

In [7]:
# Print dataset shape
df.shape

(100, 5)

In [25]:
# Filter students with math marks ≥ 80
math_marks = df[df['math'] >= 00]
math_marks

     id               name  math  english  science
0     1      Alice Johnson    85       92       78
1     2          Bob Smith    70       65       80
2     3      Charlie Brown    95       88       92
3     4       David Wilson    50       45       55
4     5       Eva Martinez    88       91       83
..  ...                ...   ...      ...      ...
95   96  Sebastian Bennett    79       81       80
96   97      Tessa Simmons    84       86       85
97   98     Ulysses Foster    92       94       93
98   99     Valeria Bryant    74       76       75
99  100        Wyatt Hayes    81       83       82

[100 rows x 5 columns]

In [26]:
# Calculate average marks per subject
average_marks = df[['math', 'english', 'science']].agg('mean')
average_marks

math       81.20
english    83.31
science    82.25
dtype: float64

In [27]:
# Sort students by science marks (descending)
sorted_science = df[['name', 'science']].sort_values(by='science', ascending=False)
sorted_science

                name  science
17       Ryan Nguyen       95
64       Nora Bryant       94
24        Yara Perez       94
84    Harper Griffin       94
44  Savannah Bennett       94
..               ...      ...
45     Tyler Simmons       67
85          Ian Diaz       67
65        Owen Hayes       67
25      Zane Roberts       66
3       David Wilson       55

[100 rows x 2 columns]

In [28]:
df.describe()

               id        math     english   science
count  100.000000  100.000000  100.000000  100.0000
mean    50.500000   81.200000   83.310000   82.2500
std     29.011492    8.764022    8.919047    8.1926
min      1.000000   50.000000   45.000000   55.0000
25%     25.750000   75.000000   78.750000   77.7500
50%     50.500000   82.500000   84.500000   83.0000
75%     75.250000   88.000000   90.000000   88.2500
max    100.000000   95.000000   95.000000   95.0000

In [29]:
# Filter students who scored less than 60 in any subject
less_than_60 = df[(df['math'] < 60) | (df['english'] < 60) | (df['science'] < 60)]
less_than_60

   id          name  math  english  science
3   4  David Wilson    50       45       55

In [34]:
# Count how many students scored above 80 in English
high_english_marks = df[df['english'] > 80][['id', 'name', 'english']]
high_english_marks

     id               name  english
0     1      Alice Johnson       92
2     3      Charlie Brown       88
4     5       Eva Martinez       91
5     6       Frank Thomas       84
7     8       Henry Walker       87
..  ...                ...      ...
94   95        Ruby Flores       90
95   96  Sebastian Bennett       81
96   97      Tessa Simmons       86
97   98     Ulysses Foster       94
99  100        Wyatt Hayes       83

[65 rows x 3 columns]

In [35]:
#Check if there are any missing values in the dataset
df.isnull().sum()

id         0
name       0
math       0
english    0
science    0
dtype: int64