In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['A', 'B', 'C', 'D', 'E']
my_list = [10, 20, 30, 40, 50]
arr = np.array([10,20,30,40,50])
d = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
pd.Series(my_list, index=labels)

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [ ]:
data={
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'], 
    'Salary': [70000, 80000, 60000, 90000]
}
df =pd.DataFrame(data)

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   60000
3    David   32      Houston   90000

In [11]:
data_list=[
    ['Alice', 24, 'New York', 70000],
    ['Bob', 27, 'Los Angeles', 80000],
    ['Charlie', 22, 'Chicago', 60000],
    ['David', 32, 'Houston', 90000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)

In [12]:
df2

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   60000
3    David   32      Houston   90000

In [13]:
df2['Name']

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [14]:
df2['City']

0       New York
1    Los Angeles
2        Chicago
3        Houston
Name: City, dtype: str

In [15]:
df2[['Name', 'City']]

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston

In [17]:
df2['designation'] = ['Manager', 'Engineer', 'Analyst', 'Director']

In [18]:
df2

      Name  Age         City  Salary designation
0    Alice   24     New York   70000     Manager
1      Bob   27  Los Angeles   80000    Engineer
2  Charlie   22      Chicago   60000     Analyst
3    David   32      Houston   90000    Director

In [21]:
df2.drop('designation', axis=1, inplace=True)

In [22]:
df2

      Name  Age         City  Salary
0    Alice   24     New York   70000
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   60000
3    David   32      Houston   90000

In [23]:
df2.drop(0, axis=0)

      Name  Age         City  Salary
1      Bob   27  Los Angeles   80000
2  Charlie   22      Chicago   60000
3    David   32      Houston   90000

In [26]:
df2.loc[[0,1]]

    Name  Age         City  Salary
0  Alice   24     New York   70000
1    Bob   27  Los Angeles   80000

In [28]:
df2.loc[3]

Name        David
Age            32
City      Houston
Salary      90000
Name: 3, dtype: object

In [29]:
df2.loc[[0,1], ['Name', 'City']]

    Name         City
0  Alice     New York
1    Bob  Los Angeles

In [30]:
df2.loc[[2,3], ['Name','Age']]

      Name  Age
2  Charlie   22
3    David   32

In [31]:
df2[df2['Age'] > 25]

    Name  Age         City  Salary
1    Bob   27  Los Angeles   80000
3  David   32      Houston   90000

In [32]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Houston')]

    Name  Age     City  Salary
3  David   32  Houston   90000

In [39]:
data = {
    'A':[1,2,np.nan,4,5],
    'B':[1, 2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [34]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [35]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [36]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [37]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [40]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [41]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [42]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [43]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [44]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [45]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [57]:
df.fillna(0, inplace=True)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [58]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [59]:
values = { 'A':0, 'B':100,'C': 300, 'D': 400}
df.fillna(value=values, inplace=True)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [60]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
import numpy as np
import pandas as pd

In [67]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name':['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department':['HR', 'Finance', 'IT', 'Marketing', 'Sales']
})
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3,6,7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [68]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna    Finance
2            3  Peter         IT
3            4  Linda  Marketing
4            5    Bob      Sales

In [69]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [71]:
pd.merge(employees, salaries, on='employee_id', how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna    Finance   80000  10000
2            3  Peter         IT   65000   7000

In [72]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna    Finance  80000.0  10000.0
2            3  Peter         IT  65000.0   7000.0
3            4  Linda  Marketing      NaN      NaN
4            5    Bob      Sales      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [73]:
pd.merge(employees, salaries, on='employee_id', how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna    Finance  80000.0  10000.0
2            3  Peter         IT  65000.0   7000.0
3            4  Linda  Marketing      NaN      NaN
4            5    Bob      Sales      NaN      NaN

In [74]:
pd.merge(employees, salaries, on='employee_id', how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna    Finance   80000  10000
2            3  Peter         IT   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [75]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']

})
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [76]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [77]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [78]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [80]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [82]:
df1=pd.DataFrame({
    'name':['Alice', 'Bob', 'Charlie']
}, index=[1, 2,3])

df2 =pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2,3,4])

In [83]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [84]:
df2

   score
2     85
3     90
4     75

In [87]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [88]:
df1.join(df2, how='inner')

      name  score
2      Bob     85
3  Charlie     90

In [89]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A','B'],
    'Store':['S1', 'S1', 'S2', 'S2', 'S1', 'S2','S2','S1'],
    'Sales':[100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity':[10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range(start='2023-01-01', periods=8)
}
df =pd.DataFrame(data)

In [90]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08